name: Build and deploy Node.js app to Azure Web App - chatbotteamsnova

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Debug npm config
        run: npm config list
      
      - name: Show Node and NPM versions
        run: |
          node -v
          npm -v
      
      - name: Install dependencies
        run: |
          npm ci
          npm ls --depth=0
      
      - name: Build app (with debug logs)
        run: |
          npm run build --if-present --verbose
        env:
          CI: true
          DEBUG: '*'
      
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BFEEF02102834B8EAD6A11945F5DDD8A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6AA9EF565D9A4697B9275D9D49C147DA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9BE5BFC2F6BF476AB864EFED1307D15F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chatbotteamsnova'
          slot-name: 'Production'
          package: './release.zip'

          




